
package client;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import business.SensorOperation;
import common.ConvertJSON;

import common.Request;
import common.Response;
import common.business.Car;
import common.business.RetractableBollard;
import common.business.infotraffic;
import common.*;

import connection.PropertiesFileReader;

import client.Frame3;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.JLabel;
import javax.swing.JToggleButton;
import javax.swing.JTextField;
import javax.swing.JTable;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.awt.Color;
import java.awt.SystemColor;

/**
 *
 * @author ANAS
 */
public class Frame3 extends javax.swing.JFrame {

	

	ArrayList<infotraffic> bollardinfo = new ArrayList<>();
	CommunicationWithServer client ;
	PropertiesFileReader serveconfig = new PropertiesFileReader();

	public Frame3(CommunicationWithServer client) throws IOException {
		getContentPane().setBackground(new Color(65, 105, 225));
		this.client= client;
		initComponents();

		
		serveconfig.initServer();

		final int SERVER_PORT = Integer.parseInt(serveconfig.getProperty("serverportClient"));
		final String SERVER_ADDRESS = serveconfig.getProperty("serveraddress");
		 lOGGER = Logger.getLogger(Frame2.class.getName());
		
		fetch(client);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		txtId = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtAlert = new javax.swing.JTextField();
		txtNbMax = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblBollard = new javax.swing.JTable();
		btnSave = new javax.swing.JButton();
		btnSave.setFont(new Font("Tahoma", Font.BOLD, 11));
		btnSave.setBackground(new Color(0, 0, 128));
		btnSave.setForeground(new Color(0, 0, 0));
		btnUpdate = new javax.swing.JButton();
		btnUpdate.setFont(new Font("Tahoma", Font.BOLD, 11));
		btnUpdate.setForeground(new Color(0, 0, 0));
		btnUpdate.setBackground(new Color(0, 0, 128));
		btnDelete1 = new javax.swing.JButton();
		btnDelete1.setFont(new Font("Tahoma", Font.BOLD, 11));
		btnDelete1.setForeground(new Color(0, 0, 0));
		btnDelete1.setBackground(new Color(0, 0, 128));
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setForeground(new Color(128, 0, 0));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Simulation");
		setResizable(false);

		jLabel1.setFont(new Font("Yu Gothic Medium", Font.BOLD, 13)); // NOI18N
		jLabel1.setText("Id");

		jLabel2.setFont(new Font("Yu Gothic Medium", Font.BOLD, 13)); // NOI18N
		jLabel2.setText("AlertAirQuality");

		jLabel6.setFont(new Font("Yu Gothic Medium", Font.BOLD, 20)); // NOI18N
		jLabel6.setText("Simulation Settings");

		tblBollard.setModel(
				new DefaultTableModel(
			new Object[][] {
			},
			new String[] {
				"Id", "AlertAirQuality", "NbMaxVehicle", "nbactuel"
			}
		) {
			Class[] columnTypes = new Class[] {
				Integer.class, Boolean.class, Integer.class, Integer.class
			};
			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
		});
		tblBollard.setCellSelectionEnabled(true);
		tblBollard.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tblStudentsMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tblBollard);
		if (tblBollard.getColumnModel().getColumnCount() > 0) {
			tblBollard.getColumnModel().getColumn(2).setResizable(false);
		}

		btnSave.setText("Save");
		btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnSave.setIconTextGap(0);
		btnSave.setInheritsPopupMenu(true);
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {

				try {
					btnSaveActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

				// TODO Auto-generated catch block

			}
		});

		btnUpdate.setText("Update");
		btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btnUpdateActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		btnDelete1.setText("Delete");
		btnDelete1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnDelete1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btnDelete1ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}
		});

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel6.setText("Simulation Settings");

		JLabel lblIsactive = new JLabel("NbMax");
		lblIsactive.setFont(new Font("Yu Gothic Medium", Font.BOLD, 13));

		JButton btnRetour = new JButton("Retour");
		btnRetour.setFont(new Font("Tahoma", Font.BOLD, 12));
		btnRetour.setForeground(new Color(0, 0, 0));
		btnRetour.setBackground(new Color(255, 255, 255));
		btnRetour.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				setVisible(false);
				MainClient launchIhm = null;
				try {client.stopConnection();

					launchIhm = new MainClient();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				launchIhm.getFrame().setVisible(true);
				
			
			}
		});
		
		lblIdBollard = new JLabel("id Bollard");
		lblIdBollard.setFont(new Font("Tahoma", Font.BOLD, 12));
		
		lblWayOfBollard = new JLabel("Way of bollard ");
		lblWayOfBollard.setFont(new Font("Tahoma", Font.BOLD, 12));
		
		lblCarId = new JLabel("Car id ");
		lblCarId.setFont(new Font("Tahoma", Font.BOLD, 12));
		
		lblCarLocation = new JLabel("Car location");
		lblCarLocation.setFont(new Font("Tahoma", Font.BOLD, 12));
		
		txtidBollard = new JTextField();
		txtidBollard.setColumns(10);
		
		testWayBollard = new JTextField();
		testWayBollard.setColumns(10);
		
		textIdCar = new JTextField();
		textIdCar.setColumns(10);
		
		textCarLocation = new JTextField();
		textCarLocation.setColumns(10);
		
		JButton btnNewButton = new JButton("Launch simulation");
		btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 14));
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btnSimulationActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
			
			
		});
		
		JLabel lblNewLabel = new JLabel("Nb actuel");
		
		textnbactuel = new JTextField();
		textnbactuel.setColumns(10);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(429, Short.MAX_VALUE)
					.addComponent(btnNewButton)
					.addGap(252)
					.addComponent(btnRetour, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
					.addGap(42))
				.addGroup(layout.createSequentialGroup()
					.addGap(363)
					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 249, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(359, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addGap(78)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(lblCarLocation)
							.addContainerGap())
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
											.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addComponent(lblIsactive)
												.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
											.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
													.addGap(1)
													.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
															.addGap(16)
															.addComponent(txtId, 188, 188, 188))
														.addGroup(layout.createSequentialGroup()
															.addGap(17)
															.addComponent(txtAlert, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE))))
												.addGroup(layout.createSequentialGroup()
													.addGap(18)
													.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(textnbactuel, GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
														.addComponent(txtNbMax, GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))))
										.addGroup(layout.createSequentialGroup()
											.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addComponent(lblWayOfBollard)
												.addComponent(lblIdBollard, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
												.addComponent(lblCarId))
											.addGap(18)
											.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(testWayBollard, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
												.addComponent(txtidBollard, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
												.addComponent(textIdCar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
												.addComponent(textCarLocation, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
									.addGap(177))
								.addGroup(layout.createSequentialGroup()
									.addComponent(lblNewLabel)
									.addPreferredGap(ComponentPlacement.RELATED)))
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
											.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
											.addGap(59)
											.addComponent(btnUpdate, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
										.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 376, GroupLayout.PREFERRED_SIZE))
									.addGap(60))
								.addGroup(layout.createSequentialGroup()
									.addComponent(btnDelete1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
									.addGap(93))))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(23)
					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
					.addGap(3)
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup()
							.addGap(65)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtId, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup()
							.addGap(35)
							.addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtAlert, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(lblIsactive)
								.addComponent(txtNbMax, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(lblNewLabel)
								.addComponent(textnbactuel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(7)
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblIdBollard)
								.addComponent(txtidBollard, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(lblWayOfBollard)
										.addComponent(testWayBollard, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
									.addGap(18)
									.addComponent(lblCarId))
								.addGroup(layout.createSequentialGroup()
									.addGap(38)
									.addComponent(textIdCar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
							.addGap(18)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(textCarLocation, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblCarLocation)))
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(btnDelete1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnUpdate, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
									.addComponent(btnRetour, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
									.addGap(44))
								.addGroup(layout.createSequentialGroup()
									.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
									.addGap(59))))))
		);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnSaveActionPerformed
		// TODO add your handling code here:
		Integer id = Integer.parseInt(txtId.getText()); // txtId.getText().trim();
		Boolean Alert = Boolean.parseBoolean(txtAlert.getText());
		Integer NbMax = Integer.parseInt(txtNbMax.getText());
		Integer nbactuel = Integer.parseInt(textnbactuel.getText());

		if (!Alert.toString().isEmpty()
				&& !NbMax.toString(NbMax).isEmpty() && !id.toString(id).isEmpty()) {
			try {
				
				final int SERVER_PORT = Integer.parseInt(serveconfig.getProperty("serverportClient"));
				final String SERVER_ADDRESS = serveconfig.getProperty("serveraddress");

				ConvertJSON converter = new ConvertJSON();

				Request req = new Request();
				infotraffic infotraffic = new infotraffic();
				
				req.setSource("client");
				req.setOperation_type("selectID");
				req.setTarget("infotraffic");
				req.setObj(id.toString());

				
				//client.startConnection(SERVER_ADDRESS, SERVER_PORT);
				
				Response resp = new Response();

				resp = client.sendMessage(req);
				ArrayList<String> info = resp.getValues();

				if (info.isEmpty()) {

					saveUser(id, Alert, NbMax,nbactuel, client);
					DefaultTableModel model = (DefaultTableModel) tblBollard.getModel();
					Object[] row = new Object[4];
					row[0] = id;
					row[1] = Alert;
					row[2] = NbMax;
					row[3] = nbactuel;
					
					model.addRow(row);
				} else {
					alert("Please provide a different id number", "Similar id found");
				}

				clear();
				//client.stopConnection();
			} catch (Exception ex) {
				Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
			} finally {
			}

		} // else if (!id.matches("^[0-9]{8}$")) {
			// alert("please provide a valid id number", "Wrong id");
			// }
		else {
			alert("please fill in all the details");
		}
	}

	// GEN-LAST:event_btnSaveActionPerformed
	private void btnSimulationActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnSimulationActionPerformed
		// TODO add your handling code here:
		Integer idBollard = Integer.parseInt(txtidBollard.getText());
		Integer idCar = Integer.parseInt(textIdCar.getText());
		Boolean BollardWay = Boolean.parseBoolean(testWayBollard.getText());
		Boolean CarLocation = Boolean.parseBoolean(textCarLocation.getText());
		
		if ( !BollardWay.toString().isEmpty() && !CarLocation.toString().isEmpty()&& !idCar.toString(idCar).isEmpty()   && !idBollard.toString(idBollard).isEmpty() ){
			
			RetractableBollard bollard = new RetractableBollard();
			 SensorOperation operation =new  SensorOperation(client);
			Car car =new Car();
			car.setId(idCar);
			bollard.setId(idBollard);
			car.setIsInTheCity(CarLocation);
			   bollard.setWay(BollardWay);
			
			
			
			try {
				operation.start(bollard,client, idCar);
				 
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
		DefaultTableModel model = (DefaultTableModel) tblBollard.getModel();
		model.setRowCount(0);
		fetch(client);
		alert("Bollard operation sucess");
		
	}
	private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnUpdateActionPerformed
		// TODO add your handling code here:
		Integer id = Integer.parseInt(txtId.getText()); 
		Boolean Alert = Boolean.parseBoolean(txtAlert.getText());
		Integer NbMax = Integer.parseInt(txtNbMax.getText());
		Integer nbactuel = Integer.parseInt(textnbactuel.getText());
		if (!Alert.toString().isEmpty()
				&& !NbMax.toString(NbMax).isEmpty() && !id.toString(id).isEmpty()) {
			try {
				
				final int SERVER_PORT = Integer.parseInt(serveconfig.getProperty("serverportClient"));
				final String SERVER_ADDRESS = serveconfig.getProperty("serveraddress");

				ConvertJSON converter = new ConvertJSON();

				Request req = new Request();
				infotraffic infotraffic = new infotraffic();
				
				req.setSource("client");
				req.setOperation_type("selectID");
				req.setTarget("infotraffic");
				req.setObj(id.toString());

				//client.startConnection(SERVER_ADDRESS, SERVER_PORT);

				Response resp = new Response();

				resp = client.sendMessage(req);
				ArrayList<String> info = resp.getValues();
				if (!info.isEmpty()) {
					

					update(id, Alert, NbMax,nbactuel, client);

					DefaultTableModel model = (DefaultTableModel) tblBollard.getModel();
					model.setRowCount(0);
					fetch(client);
					//client.stopConnection();
					alert("Update was successful");

				} else {
					alert("There is no such info", "Update error");
					clear();
				}

			} catch (Exception ex) {
				Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			alert("There is nothing to update :(", "No row selected");
		}
	}// GEN-LAST:event_btnUpdateActionPerformed

	// set the values of a row to the textfields
	private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblStudentsMouseClicked
		// TODO add your handling code here:
		int i = tblBollard.getSelectedRow();
		TableModel model = tblBollard.getModel();
		txtId.setText(model.getValueAt(i, 0).toString());
		txtAlert.setText(model.getValueAt(i, 1).toString());
		txtNbMax.setText(model.getValueAt(i, 2).toString());
		textnbactuel.setText(model.getValueAt(i, 3).toString());
		
	}// GEN-LAST:event_tblStudentsMouseClicked

	// handles delete button action
	private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnDelete1ActionPerformed
		// TODO add your handling code here:
		int i = tblBollard.getSelectedRow();
		if (i >= 0) {
			int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete?",
					"Delete confirmation", JOptionPane.YES_NO_OPTION);
			if (option == 0) {
				TableModel model = tblBollard.getModel();

				String id = model.getValueAt(i, 0).toString();
				if (tblBollard.getSelectedRows().length == 1) {
					
					delete(id,client);
					
					DefaultTableModel model1 = (DefaultTableModel) tblBollard.getModel();
					model1.setRowCount(0);
					fetch(client);
					//client.stopConnection();
					clear();
				}
			}
		} else {
			alert("Please select a row to delete");
		}
	}// GEN-LAST:event_btnDelete1ActionPerformed

	// method to show an info alert
	public void alert(String msg) {
		JOptionPane.showMessageDialog(rootPane, msg);
	}

	// method to show an error alert
	public void alert(String msg, String title) {
		JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
	}

	// method to save user to the db
	public void saveUser(Integer id, Boolean Alert, Integer NbMax,Integer nbactuel,
			CommunicationWithServer client) throws IOException {

		
		infotraffic bollard = new infotraffic();
		Request req = new Request();
		ConvertJSON converter = new ConvertJSON();
		bollard.setId(id);
		bollard.setAlert(Alert);
		bollard.setNbmaxcar(NbMax);
		bollard.setNbactuel(nbactuel);
		
		req.setOperation_type("insert");
		req.setTarget("infotraffic");
		req.setSource("");
		req.setObj(converter.infotrafficToJson(bollard));

		//client.startConnection(SERVER_ADDRESS, SERVER_PORT);

		client.sendMessage(req);
		//client.stopConnection();
		System.out.println("ok");
	}

	// update the db
	public void update(Integer id, Boolean Alert,Integer NbMax,Integer nbactuel,
			CommunicationWithServer client) throws IOException {
		try {

			final int SERVER_PORT = Integer.parseInt(serveconfig.getProperty("serverportClient"));
			final String SERVER_ADDRESS = serveconfig.getProperty("serveraddress");
			
			
			ConvertJSON converter = new ConvertJSON();

			infotraffic bollard = new infotraffic();
			Request req1 = new Request();
			ConvertJSON converter1 = new ConvertJSON();
			bollard.setId(id);
			bollard.setAlert(Alert);
			bollard.setNbmaxcar(NbMax);
			bollard.setNbactuel(nbactuel);
			req1.setOperation_type("update");
			req1.setTarget("infotraffic");
			req1.setSource("client");
			req1.setObj(converter1.infotrafficToJson(bollard));

			//client.startConnection(SERVER_ADDRESS, SERVER_PORT);

			client.sendMessage(req1);

		} catch (Exception ex) {
			Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
		}
		fetch(client);
	//	client.stopConnection();
	}

	// delete details in the db
	public void delete(String id ,CommunicationWithServer client) throws IOException {
		try {

			final int SERVER_PORT = Integer.parseInt(serveconfig.getProperty("serverportClient"));
			final String SERVER_ADDRESS = serveconfig.getProperty("serveraddress");
			infotraffic infotraffic= new infotraffic();
			Request req = new Request();
			ConvertJSON converter = new ConvertJSON();

			infotraffic.setId(Integer.parseInt(id));

			req.setOperation_type("delete");
			req.setTarget("infotraffic");
			req.setSource("client");
			req.setObj(converter.infotrafficToJson(infotraffic));

		//	client.startConnection(SERVER_ADDRESS, SERVER_PORT);

			client.sendMessage(req);

		} catch (Exception ex) {
			Logger.getLogger(Frame3.class.getName()).log(Level.SEVERE, null, ex);
		}
		fetch(client);
		//client.stopConnection();

	}

	// method to clear the txt fields
	private void clear() {
		txtId.setText("");
		txtAlert.setText("");
		txtNbMax.setText("");
		
	}

	// fetch
	private void fetch(CommunicationWithServer client) throws IOException {

		PropertiesFileReader serveconfig = new PropertiesFileReader();
		
		serveconfig.initServer();

		

		bollardinfo.clear();
		
		Request req = new Request();

		ConvertJSON converter = new ConvertJSON();
		req.setSource("client");
		req.setOperation_type("select");
		req.setTarget("infotraffic");
		

		//client.startConnection(SERVER_ADDRESS, SERVER_PORT);
		
		Response resp = new Response();
		try {

			resp = client.sendMessage(req);
			
			ArrayList<String> databollard = resp.getValues();
			ArrayList<infotraffic> data = new ArrayList<infotraffic>();

			for (int i = 0; i < databollard.size(); i++) {
				data.add(converter.JsonToinfotraffic(databollard.get(i)));

			}

			

			DefaultTableModel model = (DefaultTableModel) tblBollard.getModel();
			for (int i = 0; i < data.size(); i++) {

				Object[] row = new Object[4];
				row[0] = data.get(i).getId();
				row[1] = data.get(i).getAlert();
				row[2] = data.get(i).getNbmaxcar();
				row[3] = data.get(i).getNbactuel();
				model.addRow(row);
			}

		}

		

		catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			try {
				 CommunicationWithServer client = new CommunicationWithServer();
				new Frame3(client).setVisible(true);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDelete1;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnUpdate;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblBollard;
	private javax.swing.JTextField txtId;
	private javax.swing.JTextField txtNbMax;
	private javax.swing.JTextField txtAlert;
	private Logger lOGGER;
	private JLabel lblIdBollard;
	private JLabel lblWayOfBollard;
	private JLabel lblCarId;
	private JLabel lblCarLocation;
	private JTextField txtidBollard;
	private JTextField testWayBollard;
	private JTextField textIdCar;
	private JTextField textCarLocation;
	private JTextField textnbactuel;
}
